### ISSUE TITLE
Can't build in ubuntu 22.04

### ISSUE THREAD

**Issue by lvd2** [syncthing/syncthing#9074]
I'm trying to build syncthing in ubuntu 22.04 and it fails:

```
$ ~/d$ git clone --recursive https://github.com/syncthing/syncthing.git
Cloning into 'syncthing'...
remote: Enumerating objects: 73500, done.
remote: Counting objects: 100% (633/633), done.
remote: Compressing objects: 100% (393/393), done.
remote: Total 73500 (delta 352), reused 451 (delta 237), pack-reused 72867
Receiving objects: 100% (73500/73500), 123.30 MiB | 4.74 MiB/s, done.
Resolving deltas: 100% (51702/51702), done.

$ ~/d$ cd syncthing/

$ ~/d/syncthing$ go version
go version go1.18.1 linux/amd64

$ ~/d/syncthing$ git log | head
commit 4138e22898c4b226a029dc6cc435496857b74def
Author: Syncthing Release Automation <release@syncthing.net>
Date:   Mon Sep 4 03:45:39 2023 +0000

    gui, man, authors: Update docs, translations, and contributors

commit c42c0e7ceb67d4c35d41ad359014fe3542f532f5
Author: Maximilian <maxi.rostock@outlook.de>
Date:   Sun Sep 3 17:03:27 2023 +0200

$ ~/d/syncthing$ go run build.go
Notice: Next generation GUI will not be built; see --with-next-gen-gui.
github.com/quic-go/quic-go/internal/qtls
# github.com/quic-go/quic-go/internal/qtls
../../go/pkg/mod/github.com/quic-go/quic-go@v0.38.1/internal/qtls/go_oldversion.go:5:13: cannot use "The version of quic-go you're using can't be built using outdated Go versions. For more details, please see https://github.com/quic-go/quic-go/wiki/quic-go-and-Go-versions." (untyped string constant "The version of quic-go you're using can't be built using outdated Go...) as int value in variable declaration
note: module requires Go 1.20
github.com/syncthing/syncthing/lib/sync
# github.com/syncthing/syncthing/lib/sync
lib/sync/sync.go:119:22: undefined: atomic.Bool
note: module requires Go 1.20
github.com/syncthing/syncthing/lib/protocol
# github.com/syncthing/syncthing/lib/protocol
lib/protocol/bufferpool.go:16:16: undefined: atomic.Int64
lib/protocol/bufferpool.go:17:16: undefined: atomic.Int64
lib/protocol/bufferpool.go:18:16: undefined: atomic.Int64
lib/protocol/bufferpool.go:20:18: undefined: atomic.Int64
lib/protocol/counting.go:14:18: undefined: atomic.Int64
lib/protocol/counting.go:15:18: undefined: atomic.Int64
lib/protocol/counting.go:19:23: undefined: atomic.Int64
lib/protocol/counting.go:20:23: undefined: atomic.Int64
lib/protocol/counting.go:41:18: undefined: atomic.Int64
lib/protocol/counting.go:42:18: undefined: atomic.Int64
lib/protocol/counting.go:20:23: too many errors
note: module requires Go 1.20
exit status 2
exit status 1
```

I've also tried v1.23.7 and even v1.18.2 with the same result (failing to build)
The doc here https://docs.syncthing.net/dev/building says it is possible to build with go 1.18 and the version at the bottom of page states v1.23.7

**Comment by acolomb** [comment]
As the docs say, that was at the time of writing. Current main branch requires at least Go 1.20. Older releases not so much. You can check the release notes for when the requirements were raised.

**Comment by tomasz1986** [comment]
It would be great to have that Docs page automatically update the Go version number… I bumped it up at least a few times previously, but it seems that I forgot to do it after v1.18 😯.

**Comment by calmh** [comment]
So let's remove it and point to the source.
